name: Release

on:
  push:
    branches:
      - main
    #tags:
    #  - 'v*.*.*'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure tag points to main
        run: |
          git fetch origin main
          TAG_COMMIT=$(git rev-parse $GITHUB_REF)
          MAIN_COMMIT=$(git rev-parse origin/main)
          if [ "$TAG_COMMIT" != "$MAIN_COMMIT" ]; then
            echo "Tag is not on main branch, skipping release."
            exit 1
          fi

      - name: test before
        run: |
          echo "NODE_AUTH_TOKEN=$NODE_AUTH_TOKEN"
          ls -la /home/runner/work/_temp/

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: test after
        run: |
          echo "NODE_AUTH_TOKEN=$NODE_AUTH_TOKEN"
          ls -la /home/runner/work/_temp/
          cat /home/runner/work/_temp/.npmrc

      - name: Install dependencies
        run: npm install

      - name: QA
        run: npm run qa

      - name: Build project
        run: npm run build

      - name: Publish
        run: npm publish
